# Workflow to deploy files to an nginx server
name: Deploy to Nginx Server

on:
  push:
    branches:
      - main  # or specify your branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Nginx Server
        run: scp -i ${{ secrets.SERVER_SSH_PRIVATE_KEY }} -r * dasix@cocoformat.com:.

